# Site settings
title:       Kylie's Blog âœ¨
description: "Connecting dots... from Data to Destiny. ğŸ“ŠğŸ”®"
url:         https://kylieli.github.io

# Author
author:
  name:      Kylie
  email:     sophieli1231@gmail.com  # âš ï¸ è®°å¾—æŠŠè¿™é‡Œæ”¹æˆä½ è‡ªå·±çš„é‚®ç®±
  url:       https://kylieli.github.io

# Build settings (è¿™äº›ä¸è¦åŠ¨ï¼Œä¿æŒåŸæ ·ä»¥ç¡®ä¿ä¸»é¢˜æ­£å¸¸è¿è¡Œ)
markdown:    kramdown

# Assets
sass:
  sass_dir:  _sass
  style:     compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji # Uncomment this to allow emoji in your post

# Permalinks
permalink:   /:year-:month-:day/:title
paginate:    5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email:     sophieli1231@gmail.com  # âš ï¸ è®°å¾—æ”¹æˆä½ çš„é‚®ç®±
  github:    https://github.com/kylieli
  # twitter: https://twitter.com/yourusername  (å¦‚æœä½ æœ‰æ¨ç‰¹ï¼ŒæŠŠå‰é¢çš„ # å»æ‰å¹¶å¡«ä¸Šåœ°å€)
  linkedin:  https://www.linkedin.com/in/kaili8/ (å¦‚æœä½ æœ‰é¢†è‹±ï¼ŒæŠŠå‰é¢çš„ # å»æ‰å¹¶å¡«ä¸Šåœ°å€)/in/inela-avdic-hukic-322354131
